// Code generated by protoc-gen-go. DO NOT EDIT.
// source: platform.proto

package platform

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Class struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Topic                string     `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
	Instructor           *Teacher   `protobuf:"bytes,3,opt,name=instructor" json:"instructor,omitempty"`
	Students             []*Student `protobuf:"bytes,4,rep,name=students" json:"students,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Class) Reset()         { *m = Class{} }
func (m *Class) String() string { return proto.CompactTextString(m) }
func (*Class) ProtoMessage()    {}
func (*Class) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_3d3e4729f26223d7, []int{0}
}
func (m *Class) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Class.Unmarshal(m, b)
}
func (m *Class) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Class.Marshal(b, m, deterministic)
}
func (dst *Class) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Class.Merge(dst, src)
}
func (m *Class) XXX_Size() int {
	return xxx_messageInfo_Class.Size(m)
}
func (m *Class) XXX_DiscardUnknown() {
	xxx_messageInfo_Class.DiscardUnknown(m)
}

var xxx_messageInfo_Class proto.InternalMessageInfo

func (m *Class) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Class) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Class) GetInstructor() *Teacher {
	if m != nil {
		return m.Instructor
	}
	return nil
}

func (m *Class) GetStudents() []*Student {
	if m != nil {
		return m.Students
	}
	return nil
}

type Parent struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName            string     `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName             string     `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Email                string     `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Children             []*Student `protobuf:"bytes,5,rep,name=children" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Parent) Reset()         { *m = Parent{} }
func (m *Parent) String() string { return proto.CompactTextString(m) }
func (*Parent) ProtoMessage()    {}
func (*Parent) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_3d3e4729f26223d7, []int{1}
}
func (m *Parent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parent.Unmarshal(m, b)
}
func (m *Parent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parent.Marshal(b, m, deterministic)
}
func (dst *Parent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parent.Merge(dst, src)
}
func (m *Parent) XXX_Size() int {
	return xxx_messageInfo_Parent.Size(m)
}
func (m *Parent) XXX_DiscardUnknown() {
	xxx_messageInfo_Parent.DiscardUnknown(m)
}

var xxx_messageInfo_Parent proto.InternalMessageInfo

func (m *Parent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Parent) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Parent) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Parent) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Parent) GetChildren() []*Student {
	if m != nil {
		return m.Children
	}
	return nil
}

type Student struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName            string     `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName             string     `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Mother               *Parent    `protobuf:"bytes,5,opt,name=mother" json:"mother,omitempty"`
	Father               *Parent    `protobuf:"bytes,6,opt,name=father" json:"father,omitempty"`
	Teachers             []*Teacher `protobuf:"bytes,7,rep,name=teachers" json:"teachers,omitempty"`
	Subjects             []*Class   `protobuf:"bytes,8,rep,name=subjects" json:"subjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_3d3e4729f26223d7, []int{2}
}
func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (dst *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(dst, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Student) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Student) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Student) GetMother() *Parent {
	if m != nil {
		return m.Mother
	}
	return nil
}

func (m *Student) GetFather() *Parent {
	if m != nil {
		return m.Father
	}
	return nil
}

func (m *Student) GetTeachers() []*Teacher {
	if m != nil {
		return m.Teachers
	}
	return nil
}

func (m *Student) GetSubjects() []*Class {
	if m != nil {
		return m.Subjects
	}
	return nil
}

type Status struct {
	Success              bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_3d3e4729f26223d7, []int{3}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Teacher struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName            string     `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName             string     `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Email                string     `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Students             []*Student `protobuf:"bytes,5,rep,name=students" json:"students,omitempty"`
	Subjects             []*Class   `protobuf:"bytes,6,rep,name=subjects" json:"subjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Teacher) Reset()         { *m = Teacher{} }
func (m *Teacher) String() string { return proto.CompactTextString(m) }
func (*Teacher) ProtoMessage()    {}
func (*Teacher) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_3d3e4729f26223d7, []int{4}
}
func (m *Teacher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Teacher.Unmarshal(m, b)
}
func (m *Teacher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Teacher.Marshal(b, m, deterministic)
}
func (dst *Teacher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Teacher.Merge(dst, src)
}
func (m *Teacher) XXX_Size() int {
	return xxx_messageInfo_Teacher.Size(m)
}
func (m *Teacher) XXX_DiscardUnknown() {
	xxx_messageInfo_Teacher.DiscardUnknown(m)
}

var xxx_messageInfo_Teacher proto.InternalMessageInfo

func (m *Teacher) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Teacher) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Teacher) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Teacher) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Teacher) GetStudents() []*Student {
	if m != nil {
		return m.Students
	}
	return nil
}

func (m *Teacher) GetSubjects() []*Class {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func init() {
	proto.RegisterType((*Class)(nil), "platform.Class")
	proto.RegisterType((*Parent)(nil), "platform.Parent")
	proto.RegisterType((*Student)(nil), "platform.Student")
	proto.RegisterType((*Status)(nil), "platform.Status")
	proto.RegisterType((*Teacher)(nil), "platform.Teacher")
}

func init() { proto.RegisterFile("platform.proto", fileDescriptor_platform_3d3e4729f26223d7) }

var fileDescriptor_platform_3d3e4729f26223d7 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xbf, 0x6a, 0xe3, 0x40,
	0x10, 0xc6, 0x91, 0x6c, 0xfd, 0xf1, 0x1c, 0xf8, 0xee, 0x16, 0x17, 0x0b, 0xc7, 0x81, 0x50, 0x25,
	0x08, 0x31, 0x24, 0x69, 0xd3, 0xa5, 0x0f, 0x41, 0x4e, 0x1f, 0xd6, 0xab, 0x75, 0xbc, 0x41, 0x7f,
	0xcc, 0xce, 0xe8, 0x11, 0x52, 0xa7, 0xce, 0x13, 0xe5, 0xb5, 0x82, 0x56, 0x5a, 0x39, 0x4e, 0x30,
	0x6e, 0x42, 0xca, 0x99, 0xef, 0x27, 0xf1, 0xcd, 0x37, 0xb3, 0x30, 0xdf, 0x95, 0x82, 0x36, 0x8d,
	0xa9, 0x96, 0x3b, 0xd3, 0x50, 0xc3, 0x62, 0x57, 0xa7, 0x2f, 0x1e, 0x04, 0x37, 0xa5, 0x40, 0x64,
	0x73, 0xf0, 0x75, 0xc1, 0xbd, 0xc4, 0xcb, 0x82, 0xdc, 0xd7, 0x05, 0x5b, 0x40, 0x40, 0xcd, 0x4e,
	0x4b, 0xee, 0x27, 0x5e, 0x36, 0xcb, 0xfb, 0x82, 0x5d, 0x00, 0xe8, 0x1a, 0xc9, 0xb4, 0x92, 0x1a,
	0xc3, 0x27, 0x89, 0x97, 0xfd, 0xba, 0xfc, 0xbb, 0x1c, 0x7f, 0x7f, 0xaf, 0x84, 0xdc, 0x2a, 0x93,
	0x7f, 0x80, 0xd8, 0x39, 0xc4, 0x48, 0x6d, 0xa1, 0x6a, 0x42, 0x3e, 0x4d, 0x26, 0x87, 0x1f, 0xac,
	0x7a, 0x25, 0x1f, 0x91, 0xf4, 0xd5, 0x83, 0xf0, 0x4e, 0x18, 0x55, 0xd3, 0x17, 0x4b, 0xff, 0x01,
	0x36, 0xda, 0x20, 0x3d, 0xd4, 0xa2, 0x52, 0x83, 0xaf, 0x99, 0xed, 0xdc, 0x8a, 0x4a, 0xb1, 0x7f,
	0x30, 0x2b, 0x85, 0x53, 0x27, 0x56, 0x8d, 0xbb, 0x86, 0x15, 0x17, 0x10, 0xa8, 0x4a, 0xe8, 0x92,
	0x4f, 0xfb, 0x71, 0x6c, 0xd1, 0x79, 0x93, 0x5b, 0x5d, 0x16, 0x46, 0xd5, 0x3c, 0x38, 0xea, 0xcd,
	0x21, 0xe9, 0xb3, 0x0f, 0xd1, 0xd0, 0xfd, 0x56, 0x73, 0x19, 0x84, 0x55, 0x43, 0x5b, 0x65, 0x78,
	0x60, 0x13, 0xfd, 0xb3, 0x37, 0xd1, 0x47, 0x91, 0x0f, 0x7a, 0x47, 0x6e, 0x84, 0x25, 0xc3, 0x63,
	0x64, 0xaf, 0x77, 0xa3, 0x51, 0xbf, 0x0d, 0xe4, 0xd1, 0xe7, 0xd1, 0xdc, 0x9e, 0x46, 0x84, 0x9d,
	0x41, 0x8c, 0xed, 0xfa, 0x49, 0x49, 0x42, 0x1e, 0x5b, 0xfc, 0xf7, 0x1e, 0xb7, 0x17, 0x92, 0x8f,
	0x40, 0x7a, 0x0d, 0xe1, 0x8a, 0x04, 0xb5, 0xc8, 0x38, 0x44, 0xd8, 0x4a, 0xa9, 0x10, 0x6d, 0x14,
	0x71, 0xee, 0xca, 0x4e, 0xa9, 0x14, 0xa2, 0x78, 0x74, 0x61, 0xb8, 0x32, 0x7d, 0xf3, 0x20, 0x1a,
	0x0c, 0xfc, 0xcc, 0x8a, 0xc7, 0xf3, 0x0b, 0x4e, 0x9e, 0xdf, 0x41, 0x0e, 0xe1, 0x89, 0x1c, 0xd6,
	0xa1, 0x7d, 0x4e, 0x57, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0xca, 0x41, 0x35, 0xbe, 0x60, 0x03,
	0x00, 0x00,
}
