version: '3.7'

services:
  db:
    image: 'mysql:5'
    environment:
      MYSQL_ROOT_PASSWORD: "supersecret"
      MYSQL_USER: "soen341"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "platform"
    ports:
      - target: 3306
        published: 8081
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql


  gui:
    image: "adminer:4"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

volumes:
  mysql_data:
    external: true
